# Generated by Django 3.0.5 on 2020-12-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_auto_20201217_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title_id',
            new_name='title',
        ),
    ]
