# Generated by Django 3.0.5 on 2020-12-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_auto_20201217_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='titles', related_query_name='genres', to='apiv1.Genre'),
        ),
    ]
