# Generated by Django 3.0.5 on 2020-12-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0009_auto_20201218_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
