version: '3.8'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:12.4
    restart: unless-stopped
    env_file:
    - ./.env
    volumes:
    - postgres_data:/var/lib/postgresql/data/

  web:
    image: pashvd/yamdb_final:latest
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/

  nginx:
    image: nginx:1.19.3
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
    ports:
      - 80:80
