version: '3.3'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    restart: always
    env_file:
    - ./.env
    volumes:
    - postgres_data:/code/var/lib/postgresql/data/

  web:
    image: pashvd/yamdb_final:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static:/code/var/html/static/
      - media:/code/var/html/media/

  nginx:
    image: nginx:1.19.3
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/code/var/html/static/
      - media:/code/var/html/media/
    depends_on:
      - web
    ports:
      - 80:80
